apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: dota2-cast-assist-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 3
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: "/dota2-gsi/health"
