apiVersion: apps/v1
kind: Deployment
metadata:
  name: dota2-cast-assist-deployment
spec:
  template:
    spec:
      serviceAccountName: ksa-scrapingmartians-prod
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-central1-c
