apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dota2-cast-assist-ingress
  annotations:
    kubernetes.io/ingress.class: gce # GKE creates an external HTTP(S) load balancer (deprecated but only working)
    kubernetes.io/ingress.global-static-ip-name: dota2-cast-assist-static-ip
    networking.gke.io/pre-shared-cert: dota2-cast-assist-cert
spec:
  rules:
    - host: dota2-cast-assist.scrapingmartians.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dota2-cast-assist-service
                port:
                  number: 8082
