name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Log in to Google Artifact Registry (Docker)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACT_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t ${{ secrets.ARTIFACT_REGISTRY }}/dota2-cast-assist:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ARTIFACT_REGISTRY }}/dota2-cast-assist:latest
